### ISSUE TITLE
Sand Crafting recipe

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#10]
Trying to make the coke bricks and I need a lot of clay and sand...so JEI says sand can be made in the mortar and pestle out of gravel:
![2020-06-01_13 07 14](https://user-images.githubusercontent.com/34258851/83435034-89190280-a409-11ea-8252-b8f767b7157f.png)

Put when I put gravel in the mortar...it shows and gives me flint:
![2020-06-01_13 08 01](https://user-images.githubusercontent.com/34258851/83435094-9d5cff80-a409-11ea-9548-57deea8d1c4e.png)

I do not have the crusher yet and the coke brick needs lots of sand to make clay.

**Comment by teagan75** [comment]
there is a script error. will fix that asap

**Comment by Ladysarajane** [comment]
Okay...got the new update Beta 0.41. Look forward to this one now.

**Comment by teagan75** [comment]
this should be fixed in v0.4.1_hotfix

**Comment by Ladysarajane** [comment]
Yay! It works great. Thank you for a quick fix. I'm closing this now since it is fixed.
