### ISSUE TITLE
Hemp seeds recipe...Unintended Craft?

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#15]
Okay...you have 9 hemp seeds to make 1 harvest craft seed. Sounds good...put 9 in the crafting table pulled out a HF seed and still have 8 left in the crafting table.
![2020-06-05_20 39 28](https://user-images.githubusercontent.com/34258851/83947807-55fab880-a7e7-11ea-9add-95bc96a29aa1.png)
![2020-06-05_20 39 35](https://user-images.githubusercontent.com/34258851/83947810-598e3f80-a7e7-11ea-829f-71352fa0cf1e.png)
I added another hemp seed and pulled out another bag. Still had 8 left.  Is this intentional?

I also found that the minecolonies builder, When he clears land, He obtains all seeds that minecraft normally gets. (I obtained extra seeds (those normally in tumbleweeds)) and extra hemp seeds. I know in harvesting all that hemp, I only obtained 7 hemp seeds and the builder obtained like 40 seeds after building all my buildings. (I didn't realize he was getting them because he stuffed them on his racks and I didn't see them at first.)

**Comment by teagan75** [comment]
> I added another hemp seed and pulled out another bag. Still had 8 left. Is this intentional?

nope. I have a love/hate relationship with crafttweaker lol



> I also found that the minecolonies builder, When he clears land, He obtains all seeds that minecraft normally gets. (I obtained extra seeds (those normally in tumbleweeds)

well then, I will have to remove seed drops lol

**Comment by Ladysarajane** [comment]
Maybe a shape crafting?

**Comment by teagan75** [comment]
yeah I have already changed it

**Comment by Ladysarajane** [comment]
UGHH.....stupid crafttweaker made the craft NULL seeds
![2020-06-07_14 13 11](https://user-images.githubusercontent.com/34258851/83976619-2328f100-a8c9-11ea-862f-4b67a8ea2423.png)

**Comment by teagan75** [comment]
I think that is my fault

**Comment by Ladysarajane** [comment]
Okay...I was trying it out to make sure it worked.

**Comment by teagan75** [comment]
Thank you. My son has been particulary 3 this week and I am super distracted. I will push a hotfix asap

**Comment by Ladysarajane** [comment]
Lol.... I understand. I'm staying with my brother and his family and I have a 4yo nephew. He has been cooped up to long with his 7yo sister. My 15yo nephew (he is a JJ) has dealt surprisingly well with this quarantine. But the 4yo. Omg....he can be a terror. Lol

**Comment by teagan75** [comment]
ok the hotfix is live

**Comment by Ladysarajane** [comment]
All good now. I am going to close this since it is fixed. Thank you!
