### ISSUE TITLE
Vegatable wax

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#16]
I am using the Nordic schematic of Minecolonies in my town. In upgrading the Houses to get the kiddos I need black carpet. How ever I am unable to get black vegetable ink. I thought in Metamorphoses 1, I could cook the vegetable oil to get the vegetable wax, but in this version it is uncraftable....I need sunflower seeds. Where can I get those?

**Comment by teagan75** [comment]
You can buy cooking oil from the general store for now. I am adding the pam's hc seeds to the store now as well. When that is done I will put out a release.

Edit: Wait nvm it also needs vegetable wax

**Comment by teagan75** [comment]
Do you have any sunflowers growing in your grassy areas?

**Comment by Ladysarajane** [comment]
None...even using bonemeal or fields do not produce them. I am in a plain biome

**Comment by Ladysarajane** [comment]
Yeah, I need vegetable oil and vegetable wax. I thought in Metamorphosis 1 you had the vegetable oil be smeltable into wax.

**Comment by teagan75** [comment]
I may have made a custom recipe. I can do that again. Probably for the same reason hehe

**Comment by Ladysarajane** [comment]
Thank you! For the life of me....I couldn't think of another way to get black ink. I know there is a squid ink in Jenni's but that is only one. I need more to upgrade houses. I love the Nordic templates.

**Comment by teagan75** [comment]
Nope. No custom recipe. I think the original mod dev of Vegan Life did a better job with ore dictionary.
You are welcome! Added the recipe for next release. I love all the variety of schematics this time around.

**Comment by teagan75** [comment]
I did get the occasional sunflower in the Root's grove. I was in the plains too. I am going to make the Edible Bugs vegetable oil smeltable as well

**Comment by Ladysarajane** [comment]
That will be good to have a choice. Root's grove has never given me a sunflower yet. The luck gods must be mad at me. LOL.

**Comment by Ladysarajane** [comment]
Okay....works in the new version...I have my black carpet! Thank you!
