### ISSUE TITLE
Crafting recipe for resturaunt 

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#17]
Went to make the restaurant and an apple is required for crafting recipe. With no apples from trees it is hard to get. I was lucky to get one in Jade's room, but that is all I have. Some people may not get any. Is it possible to award one with a warning to save it?

**Comment by teagan75** [comment]
Yes. Thanks for catching that. I can also make it take a HF apple but those can only be planted in Autumn

**Comment by Ladysarajane** [comment]
And in the second year? I haven't had one available to me in Autumn of the first year.  I am in spring of my second year. I think an apple might be needed sooner.

**Comment by teagan75** [comment]
I added it as a reward but it will be in the next update

**Comment by Ladysarajane** [comment]
LOL....I made my restaurant since I was lucky to get an apple in Jade's chest and when I collect my reward...one of the rewards gave me a placeholder.
![2020-06-09_13 56 15](https://user-images.githubusercontent.com/34258851/84182963-38348a00-aa59-11ea-841f-e6da6151660b.png)
 😆 I think it was suppose to be a HF coin of some kind?

**Comment by teagan75** [comment]
fixed in v0.6.2
