### ISSUE TITLE
New Barn Quest

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#18]
I was trying to open the New Barn Quest to see what I need to start collecting. It says I need glowing dust quest to open it...so I completed that and it still didn't open. 
![2020-06-09_16 55 56](https://user-images.githubusercontent.com/34258851/84199052-87d37f80-aa72-11ea-9e9e-43e223eed17e.png)

**Comment by teagan75** [comment]
That's strange. It should have opened. There may have been a small technical issue hehe. The quest for glowing dust was accidentally set to consume the dust. There is a hidden quest that is a copy of that so unless you have a way to make it detect that it won't work.

You could run the command /bq_admin complete 66 (I think the numbers stay the same per world)

**Comment by teagan75** [comment]
run the command again for 68

**Comment by Ladysarajane** [comment]
I completed 66 and the quest opened.

**Comment by teagan75** [comment]
good. #68 opens up the mana crystal quest

**Comment by Ladysarajane** [comment]
Okay....good to know. I'll complete that too when I get back to it. My 4.yo got hold of my computer while I was away and it had been paused and didn't get killed this time...but my crops died from not being watered and my animals were all sick cause 2 wks had passed.  😠

**Comment by teagan75** [comment]
what a stinker lol. I wasn't on much because we had bad storms last night

**Comment by Ladysarajane** [comment]
> 
> 
> what a stinker lol. I wasn't on much because we had bad storms last night

He is a stinker....very independent and stubborn. He is just starting to "hold conversations" (all of our family were late talkers). Everyone else thought something was wrong with him....I'd say no...just an old family trait. They would learn the world and not repeat it until older, and suddenly start talking in whole sentences around 4- 4 1/2. As for them...we are expecting them this afternoon. Amateur Radio Skywarners have already told us we would be on alert this afternoon. We had a couple storms yesterday...but today they are telling us Tornado's are likely and more widespread for the area.
  Sat on the porch this morning to drink my coffee and the atmosphere feels charged. .  So I will play a bit and check the sky ever so often. But I might not be on later either. Depends on the weather.

**Comment by teagan75** [comment]
We had to go in our crawl space last night. The funnel cloud went right over us but it was swift. No damage thankfully. There is a pretty severe storm going on right now too

**Comment by Ladysarajane** [comment]
Ugh......that is not good. I've been in two tornado's. Not good....one was in a tent while camping. The other one was in 1974 during the big outbreak. They do sound like trains. Was in a third one we think while driving. My mom saw a "cloud" look like it was touching a fence....it paralleled us, then it "crossed the street' in front of us and uprooted a huge tree by it's roots. Missed the front of our car and another car in the other direction by inches. Since it was fair weather then...they tried to say the tree was old. The other car and us tried to tell them at the time...the tree went straight up..pulled up. Not leaned. Even the tree cutters tried to say the tree was old...but no rot in it. No reason for it to fall. That was an adventure when your 7yo. LOL.

Stay safe...sounds like a bumpy day ahead for both of us.

**Comment by teagan75** [comment]
this should be fixed in v0.6.2
