### ISSUE TITLE
Cow quest

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#2]
On the cow quest, I did not get credit for either the brush or milker when I held them. I don't know if you have to hold both of them unused in your hand to get credit for them but you have to use the brush before he gives you the milker. I got credit for the trough, but not the brush or milker.

**Comment by teagan75** [comment]
ok I will set it to ignore damage. You can manually push the quest through if you know how

Edit: Cannot change it to ignore damage because that changes the item. I just rearranged the quest tasks

**Comment by Ladysarajane** [comment]
Okay...I just bought another brush and milker from Jim and it registered that. I don't know if you have the same problem...but the Farming Book...my book doesn't registered my animals in the Relationship tabs. Do you know if that is a problem with the Harvest Festival update? Keeps telling me no animals near, even though I am standing right next to them. It registers when I talk to people.

Edit....okay after a couple in game days...cow finally showed up. Chicken still not present.

![2020-05-28_09 16 22](https://user-images.githubusercontent.com/34258851/83146236-feac6800-a0c3-11ea-958b-88ad7512610f.png)

**Comment by teagan75** [comment]
Ok I was going to say my cow showed up right away in the book

**Comment by Ladysarajane** [comment]
You have to be practically on top of them for them to show up. If I leave the pen...they will not show up. Also it doesn't show if you feed or talk, brush or treat them like in 1.7.2. I guess they are still working on it.

**Comment by Ladysarajane** [comment]
Does yours say the entity.cow.name ? When I am near my chicken it says entity.chicken.name
I am assuming this must be a bug with Harvest Festival 1.12

**Comment by teagan75** [comment]
Yes my book does say that

**Comment by Ladysarajane** [comment]
I will report this on their issue tracker. I don't think he will fix..but we will see. I hadn't seen it as an issue.

**Comment by teagan75** [comment]
The issue with the Rancher quest should be fixed in v0.3_beta
