### ISSUE TITLE
Tek Topia quests not completing

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#21]
The TekTopia quests are not recognizing for the quests. Finally got my Town Hall going and took the tokens out of the box and the quest doesn't recognize them. 
![2020-06-15_19 08 12](https://user-images.githubusercontent.com/34258851/84714523-ec438280-af3b-11ea-80e7-07fc08a69ef7.png)
![2020-06-15_19 08 21](https://user-images.githubusercontent.com/34258851/84714531-f1083680-af3b-11ea-954b-2a521ceb4c9d.png)
![2020-06-15_19 08 43](https://user-images.githubusercontent.com/34258851/84714535-f49bbd80-af3b-11ea-8dcc-2befadae4d7f.png)

I tried even to detect them and it wouldn't go.

**Comment by Ladysarajane** [comment]
First off.....for information...I built a Town Hall. I feel that the guild hall might be better for a tavern later with the bard..once I get a jukebox. Just need to replace some of the "chairs" with Tektopia chairs....Also minor warning. In my town hall, I had it decorated a bit, with a table and chairs. I activated my town hall and the chest that spawns in destroyed my chair...not a biggy...just surprised. It was those tokens in the chest that the Quest book wouldn't recognize. I pulled one of each out of creative and it recognized those...so I guess it is meta data?

**Comment by teagan75** [comment]
> First off.....for information...I built a Town Hall. I feel that the guild hall might be better for a tavern later with the bard..once I get a jukebox.

I have schematics for a tavern later on.



> It was those tokens in the chest that the Quest book wouldn't recognize. I pulled one of each out of creative and it recognized those...so I guess it is meta data?

ugh all these mods and their metadata lol

**Comment by Ladysarajane** [comment]
Yeah...I thought that might be the cause...so I did some troubleshooting to see if it was. 
If you have a tavern for later.....I might go ahead and use my backup when you fix the "metadata problem" and rearrange my town hall. I can use my building for another house down the road.

**Comment by teagan75** [comment]
i just relaeased 0.6.5

**Comment by Ladysarajane** [comment]
It works 👍 .  I'll close this out now.
