### ISSUE TITLE
Blacklisted mob

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#23]
Kinda confused. I was summoning my cows...and I went to pick the cow up with the lasso that was a reward and I got a "this mob is blacklisted" But it spawned from the ritual? 

![2020-06-20_15 43 56](https://user-images.githubusercontent.com/34258851/85210355-30080480-b30d-11ea-990b-45e28b2e6f88.png)

I haven't tried the pigs yet.

**Comment by teagan75** [comment]
Yes I missed changing that to a soulstone. The reason it is blacklisted is because I don't want players using farm animals in mob farms. I will change that tomorrow. I was really busy today.

**Comment by Ladysarajane** [comment]
So it was actually the lasso that had them blacklisted. I can understand being busy. :smile:

**Comment by Ladysarajane** [comment]
Another problem. I cannot summon a pig. Quest book says I need a mud block and beet root on offering plates, which I have, but it says those items are incorrect. 

![2020-06-21_09 41 45](https://user-images.githubusercontent.com/34258851/85226155-0221cf00-b3a4-11ea-9a1b-43a11eed3881.png)

**Comment by teagan75** [comment]
Does the beetroot have any extra data attached to it? NBT data? and is the mud wet mud not dry?

**Comment by Ladysarajane** [comment]
![2020-06-21_11 50 36](https://user-images.githubusercontent.com/34258851/85229098-d4458600-b3b5-11ea-81ed-8c70f666cff4.png)
I don't think the beetroot has metadata (it was the two beetroots given as a reward) and the mud is dry. Quest book calls for Mud Block not Wet Mud block. I will try the wet blocks

**Comment by teagan75** [comment]
ok that could be my issue then

**Comment by Ladysarajane** [comment]
The Wet Mud block worked. Just need to add the word Wet to the quest description. 
![2020-06-21_11 57 16](https://user-images.githubusercontent.com/34258851/85229230-8d0bc500-b3b6-11ea-973c-b43b83e569f3.png)

**Comment by teagan75** [comment]
both these issues should be resolved in v0.6.5.3
