### ISSUE TITLE
Silver Hammer Quest

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#24]
I've had the silver hammer for a while and when the quest came up, of course it didn't recognize it. I mended the hammer (which worked for the axe and watering can, but it still didn't recognize it. I am assuming meta data is playing a role (it is ready to upgrade to gold)

I am trying to get a second hammer and upgrade it to silver, it is just taking me awhile.

**Comment by teagan75** [comment]
I will take a look

**Comment by teagan75** [comment]
Let me know if this is fixed in v0.6.5.3

**Comment by Ladysarajane** [comment]
This now works....however, the silver axe isn't working and I assume the silver watering can you may want to check too as that is after the silver axe.

**Comment by teagan75** [comment]
The copper ones worked? I will go ahead and change them all
