### ISSUE TITLE
Carpenter reset store, when log out of the game.

### ISSUE THREAD

**Issue by Nerden03** [teagan75/Metamorphoses-2#25]
Hi, love the pack. I'm on version 0.6.5.3_beta, version 1.12.2. I had a problem with the single-player game. When I quit the game and come back to the carpenter store it had reset back to the start options for the blueprints. It seemed to be fixed when I loaded an older version of the Harvest Festival Legacy mod. From 0.6.20 to 0.6.18, and can now progress in the mod.

**Comment by Ladysarajane** [comment]
Hmmm.....I have not had that problem in my testing of the pack with my different single player worlds. Did you have any download hiccups when downloading it originally? I am wondering if the original download messed up somewhere.

**Comment by teagan75** [comment]
I have never come across this in all my worlds. I would have to agree with Ladysarajane that it is most likely a random hiccup with downloading or reading data. Hopefully it hasn't happened again for you
