### ISSUE TITLE
Fey Crafter reward

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#26]
Under the Hamlet quest line, under the Grove you need to make a Fey Crafter and the reward is a Fey Crafter. Do we need two Fey Crafters? I have started another world and so far no problems with the quests. I just was curious about this award.

**Comment by teagan75** [comment]
no you don't need two fey crafters hehe. Will come up with a different reward.

**Comment by teagan75** [comment]
fixed in v0.6.5.4
