### ISSUE TITLE
Jade got cheap

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#27]
As you know in working with Modii, that Jade now only gives Hardy Turnips in exchange for flowers. It was not that way in earlier versions....not sure why she is doing it this way now. I have started two more worlds....and that is what it is doing now. Need someway to alert people to hang on to one of the reward turnips to finish the quest in the second quest line or give the ability to Jade's store to sell limited regular turnips. I am assuming what Jade gives in exchange for flowers is not editable? 

Hope you are doing well. Love hearing JJ asking for ice cream. 🤣 Sounds like my nephew.

**Comment by teagan75** [comment]
Yeah that kinda caught me by surprise! I do think I can edit what she gives or I am going to try hehe

**Comment by Ladysarajane** [comment]
Yeah....not sure when that happened, I was surprised, and so I tested it too and came up with the same results on two new worlds.

**Comment by Ladysarajane** [comment]
New development. Now at the end of summer, I talked to her....I did not have the flowers in my hand...but she took them and gave me a bag of onions. I do not have the basic friendship with her either (I haven't obtained the toast recipe yet)....she has never given me onions before.

**Comment by teagan75** [comment]
Something changed for sure lol. I have made a few notes and I am working
through them :)

**Comment by teagan75** [comment]
So, I cannot change this part of the game mechanic. It's just weird how it changed. There hasn't been an update since April. I am going to remove the quest but tell players they can still get seeds for flowers.

**Comment by Ladysarajane** [comment]
That is fine with me. I was lucky that I had not planted all my turnips yet to complete that quest.

**Comment by teagan75** [comment]
Changed the quest in version 0.6.5.4
