### ISSUE TITLE
Obtaining salt

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#28]
You and Modii are trying to get leather to finish that crate quest. First with the making of leather you need salt....I cannot figure a way to get it, without the general store. 
For me to finish that quest, I just "borrowed" the item frames from the carpenters house. (one holding the tool and one on the bench.)

Is there a way to obtain salt before Jenni's general store  is built that I cannot see?

**Comment by teagan75** [comment]
Was pretty sure Pam’s HC had a way

**Comment by Ladysarajane** [comment]
I just had a senior moment there...I thought I looked up salt and I couldn't find the recipe.  It is there. Just checked it out. I made the pot and made salt. Now I can make more crates! 😄
