### ISSUE TITLE
Weapons Rack

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#31]
I've always used the weapons racks sold by the blacksmith. Never had a problem. Now I have bought them and tried to put them up in my ranch house and they disappear. I hear a sound like they are being placed....but no rack. Logged out and back in...restarted the game and no racks. I tried it on the brick, then on the spruce planks....Nothing. 

I've used them before and had no problems. Not sure what is going on.

Edit: After playing with it..it seems to be associated with a particular wood one. The acacia one is okay. I am still testing the other ones...I will get the id of the item soon. 

Edit: A couple of the first ones that placed have now disappeared. Not sure what is going on.  I have moved to Overwolf launcher. I wonder if that is affecting downloads of the mods with the packs?

**Comment by teagan75** [comment]
the move to overwolf has definitely messed with some things. I purchased a rack and placed it fine so I am not sure at this point

**Comment by Ladysarajane** [comment]
I am going to close this topic....it seems that now with Overwolf has settled a bit, this is no longer a issue. Placing the racks without problems now.
