### ISSUE TITLE
City quest line

### ISSUE THREAD

**Issue by DodgerWoman26** [teagan75/Metamorphoses-2#32]
Not sure what kind of issue this would be lol. I finished all the quests in City (went ahead and cheated in the wheat and spiritual herb for the sake of moving on) All the quests are green and no final chapter quest has opened, nor has the next chapter -Metro- to allow me to move on....

**Comment by teagan75** [comment]
could I have a screenshot of the city chapter?

**Comment by teagan75** [comment]
nvm i think i figured it out

**Comment by DodgerWoman26** [comment]
Let me know if you do need it, always happy to help :)

**Comment by teagan75** [comment]
This should be fixed in v0.6.5.4
