### ISSUE TITLE
Deer Antlers useful?

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#5]
Hi Teagan...I have made a new instance to play beta 0.3
So far everything is working fine. Dumb me didn't read the quest book good enough about tumbleweeds (I just thought they were ambience) and now I am chasing them all over the place...LOL
I finally started having the mystical lib animals spawn and I know what the beetles are for...but the deer, other than the venison and the leather...what are the antlers for? I can't find a recipe using them. If there is no use for them, maybe add them to the compost bin recipes?

**Comment by teagan75** [comment]
I am not sure about antlers. Have you looked in the mystical world book? I could have them be ground into bonemeal with more yield than regular bones. I do want most items useful

**Comment by Ladysarajane** [comment]
I did and there is nothing on antlers. Maybe something to make brown dye? Not sure what is in the pack to make brown dye...Either that or bonemeal.

**Comment by teagan75** [comment]
Cocoa seeds can be attained through transmutation in Roots however it uses dead bushes lol. Maybe I should add that to the tumbleweeds and compost too. 

Edit: I thought if you put four jungle saplings down in 2x2 it would grow into a large tree with vines and occasionally cocoa seeds

**Comment by teagan75** [comment]
I have also added the aubergine seed to the general store. The restaurant recognizes it as food and cooks it. I wonder if the farmer would plant it. Then we would have a use for a farmer

**Comment by Ladysarajane** [comment]
In version 1, I never got cocoa seeds...only vines. I haven't made the 2x2 jungle saplings yet in this version. I  will try it either tonight or tomorrow morning. Dodging storms again today so grabbing play time when I can..LOL. That would be a good use for the farmer. The rice and flax in  the general store...can they be grown at all?

**Comment by teagan75** [comment]
Yes they can be grown plus grown without cropsticks. Ah I see rice can be cooked into bread. Another good use for the farmer if they will recognize the crop

**Comment by Ladysarajane** [comment]
I will try the farmer hopefully tomorrow and find out. Trying to sneak the jungle tree in. I have been unlucky getting saplings from my jungle trees so I had to wait till I got the General store...LOL. Aubergine seeds will come in next version right?

**Comment by teagan75** [comment]
Yes

**Comment by teagan75** [comment]
There really is no reason why I can’t just add cocoa seeds to the general store lol

**Comment by Ladysarajane** [comment]
Yeah....cause tried to grow the 2x2 tree....did the dance around the saplings...stack of bonemeal and it won't grow. I don't have the tree farm yet.

**Comment by teagan75** [comment]
Antlers give bonemeal and Aubergine/cocoa seeds are in the general store v0.4
