### ISSUE TITLE
Rancher Quest Again

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#6]
Rancher quest is not registering again. Kinda odd though. When Jim gave me the fodder and animal brush...it said on it completed. So I used them and got the milker...didn't check the quest book, then...before I used the milker..Somehow the fodder and animal brush became unchecked. I guess after I used them on the cow to be able to get the milker it became unchecked? I should have checked after I used them about that. 

Actually I believe it is the ID of the animal brush Jim gives you not matching. I used a backup and did it again..and The Brush didn't registered, but the fodder did. I had a brush in the item frame in the barn and I tried that and it wouldn't registered. The brush that you buy from Jim is the one that it registers as completed. If you use the milker to be able to buy the brush..then the milker becomes invalid and you have to buy not only the brush, but the milker too along with another piece of fodder to complete the quest.

**Comment by teagan75** [comment]
That is so weird. This quest had no issues in the previous version. Can you screenshot the id? Hover over the brush with your mouse and screenshot it?

**Comment by Ladysarajane** [comment]
It wasn't giving me an id.
![2020-05-30_09 00 44](https://user-images.githubusercontent.com/34258851/83328859-2d594880-a254-11ea-9ecf-ce70016487fb.png)
![2020-05-30_09 01 02](https://user-images.githubusercontent.com/34258851/83328861-30543900-a254-11ea-9b78-b9d468cdd3b6.png)

Is there a setting in minecraft for me to get it to show? Maybe I need to be in creative?

**Comment by teagan75** [comment]
F3 plus H I believe shows info but I can do it later as well.

**Comment by Ladysarajane** [comment]
Okay....cause I cannot seem to get it to show.....F3 and H did not show it for me.

That is suppose to do..but for some reason, I can't seem to do it.

Do you have optifine? Apparently that is the way to get advance tool tips?

**Comment by Ladysarajane** [comment]
I installed optifine..
This is what I got:
Item bought from Jim:
![2020-05-30_09 39 16](https://user-images.githubusercontent.com/34258851/83329821-91324000-a259-11ea-83d8-f92ac6e5d6cb.png)

Item given to me from Jim and used on cow once:
![2020-05-30_09 39 25](https://user-images.githubusercontent.com/34258851/83329826-95f6f400-a259-11ea-9b57-83fdeb021b96.png)

**Comment by teagan75** [comment]
Looks like the NBT tag stores data. I will set the quest to ignore that and hopefully that solves it

**Comment by Ladysarajane** [comment]
Don't forget to adjust the fodder to 15. Jim gives you 16 ...but you use one to complete that part 1 of the quest.  If you use the fodder the quest won't complete when you get the milker, before you have to use it and buy another milker

**Comment by teagan75** [comment]
i noticed that too

**Comment by teagan75** [comment]
Let's hope this quest is finally fixed in v0.4

**Comment by Ladysarajane** [comment]
Try, try again. :). I will test v0.4 when it comes out.

**Comment by Ladysarajane** [comment]
Just got the new version and it Worked!!! So this can be closed now.
