### ISSUE TITLE
Question about compressed dirt

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#7]
I could have sworn that you could uncompressed dirt into 9 dirt blocks. You can take double compressed dirt and decompress that into compressed dirt...but now I cannot decompress compressed dirt. Did you change this? 
By the way...like the repeatable quest to update the Quest book, and that you added the farmer. My colonists are way too hungry!!!!

Trying to decompress compress dirt into dirt:
![2020-05-30_16 25 33](https://user-images.githubusercontent.com/34258851/83338491-f0607680-a292-11ea-9901-833722693d35.png)

Decompressing double compressed dirt into compressed dirt:
![2020-05-30_16 25 44](https://user-images.githubusercontent.com/34258851/83338496-f35b6700-a292-11ea-8056-12008704c91e.png)

**Comment by teagan75** [comment]
> I could have sworn that you could uncompressed dirt into 9 dirt blocks. You can take double compressed dirt and decompress that into compressed dirt...but now I cannot decompress compressed dirt. Did you change this?

Yes I changed it because you could completely bypass the compost bin to get dirt. Later on I allow it through Nature's Aura.




> By the way...like the repeatable quest to update the Quest book, and that you added the farmer. My colonists are way too hungry!!!!

I know my colonists were too

**Comment by Ladysarajane** [comment]
Okay.....I was wanting to fix a place in my village and I only had compressed dirt on me at the time... I'll close this now.
