### ISSUE TITLE
Staff not recognized for Imbuer Quest completion 

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#8]
Beta Version 0.4
Made a staff and the quest book doesn't recognize it. 
![2020-05-31_17 50 45](https://user-images.githubusercontent.com/34258851/83363432-63d3b800-a367-11ea-8c02-b4c584047d25.png)

It completed the imbuer, but not the staff. Also it says to put a stick in the imbuer and the petal dust and you can get the wand...it won't let me do that either. 
![2020-05-31_17 54 57](https://user-images.githubusercontent.com/34258851/83363520-0f7d0800-a368-11ea-8867-022cc12d4b70.png)

**Comment by teagan75** [comment]
stick first then petal dust

Edit: nvm I didn't change the conversation from 1.10, all you do is craft the staff now. Then you put the staff in the imbuer with the petal dust for grove supplication. Then it should work

**Comment by Ladysarajane** [comment]
Okay...so it is looking for the Imbued Staff...I'll try it.

**Comment by Ladysarajane** [comment]
I made the imbued staff and it still didn't accepted it.

**Comment by teagan75** [comment]
the imbued staff is the next quest. I think I have to remove NBT data for some reason. idk why it has nbt data at this point

**Comment by Ladysarajane** [comment]
Not sure why either. Just made it in the crafting table and waiting for the ding and nothing...I picked up the imbuer and nothing.

**Comment by teagan75** [comment]
I am going to try and finish the Metropolis chapter today and then put out another update. I have to record with Modii this morning and depending on how much he wants to chat will determine when I can get an update out 😉

**Comment by Ladysarajane** [comment]
That's good....:)  Except for chatty Modii. I hope he isn't tooo chatty today. LOL

**Comment by teagan75** [comment]
I didn't finish Metropolis chapter but still released v0.4.1 Hopefully the quest is fixed

**Comment by Ladysarajane** [comment]
This is fixed...no problems with it now.
